language: python
sudo: false
os:
  - linux

python:
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - "PYTHONPATH=. py.test tests/*"

notifications:
  webhooks:
    urls:
      - https://rmotr.com/api/v1/webhooks/travis/build-project
    on_success: always
    on_failure: always
    on_start: never